title: BUKA GIS
description: Tempat sharing tips n trick mengelola data spasial
url: https://www.bukagis.web.id
baseurl: "" 
theme: null
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


permalink: /:categories/:title/
# Opsi tema minimal, biarkan default untuk pemula
minimal_mistakes_skin: default
markdown: kramdown
