title: BUKA GIS
description: Tempat sharing tips n trick mengelola data spasial
url: https://dwiyan58.github.io/bukagis/  # ganti dengan domainmu nanti
baseurl: /bukagis
theme: null
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:categories/:title/
# Opsi tema minimal, biarkan default untuk pemula
minimal_mistakes_skin: default
markdown: kramdown
